apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: s12
type: Opaque
stringData:
  DB_USER: "admin"
  DB_PASS: "s3cr3t-p@ss"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-demo
  namespace: s12
spec:
  replicas: 1
  selector:
    matchLabels: { app: secret-demo }
  template:
    metadata:
      labels: { app: secret-demo }
    spec:
      containers:
        - name: web
          image: nginx:alpine
          ports: [{ containerPort: 80 }]
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef: { name: app-secret, key: DB_USER }
            - name: DB_PASS
              valueFrom:
                secretKeyRef: { name: app-secret, key: DB_PASS }
