apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-running
  namespace: s10
spec:
  containers:
    - name: web
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-succeeded
  namespace: s10
spec:
  restartPolicy: Never
  containers:
    - name: job
      image: busybox:stable
      command: ["sh", "-c", "echo hello-pod-lifecycle && sleep 2"]
---
apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-failed
  namespace: s10
spec:
  restartPolicy: Never
  containers:
    - name: fail
      image: busybox:stable
      command: ["sh", "-c", "echo boom && exit 1"]
