apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-demo
  namespace: s10
  labels: { app: rolling-demo }
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 1, maxSurge: 1 }
  selector:
    matchLabels: { app: rolling-demo }
  template:
    metadata:
      labels: { app: rolling-demo }
    spec:
      containers:
        - name: web
          image: nginx:alpine
          ports: [{ containerPort: 80 }]
