name: Hello Github Actions
on:
    workflow_dispatch
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Print message
              run: echo "Hello from Github Actions"
            - name: Show Date
              run: date
            - name: Show operating system
              run: uname -a

    mello:
        runs-on: ubuntu-latest
        steps:
            - name: Print hello
              run: echo "Narendra" 


            